version: "3.8"

services:
  postgresserver:
    image: postgres
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: postgres
      POSTGRES_DB: customerdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - customer_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 10s
      retries: 5
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      postgresserver:
        condition: service_healthy
    environment:
      - RUNENVIRONMENT=production
    networks:
      - customer_network

networks:
  customer_network:
    driver: bridge

volumes:
  postgres-data:
